SIGC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views 
from xauth import views as xauth_views
from django.views.i18n import JavaScriptCatalog



MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")




urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='logout'),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path('retour/', views.back_button_view, name='back-button'),
    # path(
    #     "account-activation/<uuid:pk>/set-password/",
    #     xauth_views.SetPasswordView.as_view(),
    #     name="user-set-password",
    # ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

ie_app/urls.py
from django.urls import path

from ie_app import views

app_name = "ie_app"

urlpatterns = [
    path(
        "export/<str:model_name>/<int:with_data>/",
        views.ExportView.as_view(),
        name="export-view",
    ),
    path(
        "import/<str:model_name>/",
        view=views.ImportView.as_view(),
        name="import-view",
    ),
    path(
        "confirm-import/<str:model_name>/",
        view=views.ConfirmImportView.as_view(),
        name="confirm-import-view",
    ),
    
]

web/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from web import views
from xauth import views as auth_views

handler400 = "web.errors_views.handler_400_view"
handler403 = "web.errors_views.handler_403_view"
handler404 = "web.errors_views.handler_404_view"
handler500 = "web.errors_views.handler_500_view"

MEDIA_ROOT = getattr(settings, "MEDIA_ROOT")
MEDIA_URL = getattr(settings, "MEDIA_URL")
ONLINE = getattr(settings, "ONLINE")

urlpatterns = [
    path("", views.CustomRedirectView.as_view(), name="redirect-index"),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemaps},
    #     name="django.contrib.sitemaps.views.sitemap",
    # ),
    path("home/", views.IndexTemplateView.as_view(), name="index-view"),
    path("admin/", admin.site.urls),
    path("parameters/", include("parameter.urls")),
    path("import-export/", include("ie_app.urls")),
    path("auth/", include("xauth.urls")),
    path("login/", auth_views.CustomLoginView.as_view(), name="user-login"),
    path("signup/", auth_views.User2CreateView.as_view(), name="user-signup"),
    path("logout/", auth_views.CustomLogoutView.as_view(), name="user-logout"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        auth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "password-reset/request/",
        auth_views.CustomPasswordResetView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/request-done/",
        auth_views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-request-done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

ie_app/forms.py
from django import forms
import os.path
class SomeImportForm(forms.Form):
    import_file = forms.FileField(label="Select file to import")
    """format = forms.ChoiceField(
        choices=[(i, fmt().get_title()) for i, fmt in enumerate(get_import_formats())],
        label="File format"
    )"""

class ConfirmImportForm(forms.Form):
    import_file_name = forms.CharField(widget=forms.HiddenInput())
    original_file_name = forms.CharField(widget=forms.HiddenInput())
    format = forms.CharField(widget=forms.HiddenInput())
    resource = forms.CharField(widget=forms.HiddenInput(), required=False)

    def clean_import_file_name(self):
        data = self.cleaned_data["import_file_name"]
        data = os.path.basename(data)
        return data

ie_app/views.py
from datetime import date

from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from django.views.generic import View, FormView
from django.apps import apps
from django.urls import reverse, reverse_lazy
from ie_app.forms import *
from import_export.formats import base_formats
import zipfile

from import_export import (
    forms as ie_forms,
    tmp_storages as ie_tmp_storages,
    mixins as ie_mixins,
    results as ie_results,
    admin as ie_admin,
    resources as ie_resources,
)
from tablib import Dataset
from formset.views import FormViewMixin

from ie_app.resources import resource_classes
from ie_app import resources

# Create your views here.

@method_decorator([require_http_methods(["GET"])], name="get")
class ExportView(View):
    def get(self, request, model_name: str, with_data=1, *args, **kwargs):
        try:
            model = apps.get_model(model_name)
        except Exception:
            messages.error(request, "Impossible d'exporter cette table.")
            return redirect(request.META.get("HTTP_REFERER"))

        try:
            resource_class = resource_classes.get(model.__name__, resource_classes["default"])
            resource = ie_resources.modelresource_factory(model=model, resource_class=resource_class)
        except KeyError:
            resource = ie_resources.modelresource_factory(model=model, resource_class=resource_classes["default"])

        if not resource:
            messages.error(request, "Impossible d'exporter les données de cette table.")
            return redirect(request.META.get("HTTP_REFERER"))

        resource = resource(with_data=with_data, request = self.request)
        if with_data == 1:
            queryset = resource.get_queryset()
        else:
            queryset = resource.get_none()

        if not queryset.exists() and with_data == 1:
            messages.warning(request, "Aucune donnée à exporter.")
            return redirect(request.META.get("HTTP_REFERER"))

        dataset = resource.export(queryset=queryset)
        export_format = base_formats.XLSX()
        export_data = export_format.export_data(dataset)
        file_name = f"{model._meta.verbose_name_plural.lower()}{'' if with_data else '-modele'}-{date.today().isoformat()}.xlsx"
        return HttpResponse(
            content=export_data,
            content_type=export_format.get_content_type(),
            headers={"Content-Disposition": f'attachment; filename="{file_name}"'},
        )

"""@method_decorator([require_http_methods(["GET"])], name="get")
class ExportView(View):
    def get(self, request, model_name: str, with_data=1, *args, **kwargs):
        # model_name : <app_label>.<model_name>
        try:
            model = apps.get_model(model_name)
        except Exception:
            messages.error(request, "Impossible d'exporter cette table.")
            return redirect(request.META.get("HTTP_REFERER"))

        try:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes[model.__name__]
            )
        except:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes["default"]
            )

        if not resource:
            messages.error(request, "Impossible d'exporter les données de cette table.")
            return redirect(request.META.get("HTTP_REFERER"))

        resource = resource(with_data=with_data)
        if with_data == 1:
            queryset = resource.get_queryset()
        else:
            queryset = resource.get_none()

        if not queryset.exists() and with_data == 1:
            messages.warning(request, "Aucune donnée à importer.")
            return redirect(request.META.get("HTTP_REFERER"))

        dataset = resource.export(queryset=queryset)
        file_name = f"{model._meta.verbose_name_plural.lower()}{'' if with_data else '-modele' }-{date.today().isoformat()}.xlsx"
        return HttpResponse(
            content=dataset.xlsx,
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={f"Content-Disposition": f'attachment; filename="{file_name}"'},
        )"""


class ImportView(ie_mixins.BaseImportMixin, FormView):
    form_class = ie_forms.ImportForm
    confirm_form_class = ie_forms.ConfirmImportForm
    template_name = "import.html"

    def dispatch(self, request, *args, **kwargs):
        model_name = self.kwargs.get("model_name")
        print(model_name)

        try:
            model = apps.get_model(model_name)
        except Exception:
            messages.error(self.request, "Impossible d'importer cette table.")
            return redirect(self.request.META.get("HTTP_REFERER"))

        try:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes[model.__name__]
            )
        except:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes["default"]
            )

        if not resource:
            messages.error(
                self.request, "Impossible d'exporter les données de cette table."
            )
            return redirect(self.request.META.get("HTTP_REFERER"))

        self.model = model
        self.resource = resource()

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_name"] = self.model._meta.label_lower
        context["fields_list"] = [
            (
                resource.get_display_name(),
                [f.column_name for f in resource.get_user_visible_fields()],
            )
            for resource in [self.resource]
        ]
        return context

    def write_to_tmp_storage(self, import_file, input_format):
        encoding = None

        tmp_storage = ie_tmp_storages.TempFolderStorage(
            encoding=encoding, read_mode=input_format.get_read_mode()
        )
        data = bytes()
        for chunk in import_file.chunks():
            data += chunk

        # if tmp_storage_cls == MediaStorage and not input_format.is_binary():
        #     data = data.decode(self.from_encoding)

        tmp_storage.save(data)
        return tmp_storage
    def get_import_resources(self):
        return [self.resource]
    
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.get_import_formats(), self.get_import_resources(), **self.get_form_kwargs())

    """def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.get_import_formats(), **self.get_form_kwargs())"""

    def get_success_url(self):
        model_name = self.kwargs.get("model_name")
        return reverse(f"app:import-view", kwargs={"model_name": model_name})

    def form_valid(self, form):
        import_formats = self.get_import_formats()

        import_file = form.cleaned_data["import_file"]
        input_format = import_formats[int(form.cleaned_data["format"])]()

        dataset = Dataset()
        imported_data = dataset.load(import_file)

        result: ie_results.Result = self.resource.import_data(
            imported_data,
            collect_failed_rows=True,
            dry_run=True,
            rollback_on_validation_errors=True,
            use_transactions=True,
        )

        tmp_storage = self.write_to_tmp_storage(import_file, input_format)
        import_file.tmp_storage_name = tmp_storage.name
        context = self.get_context_data()

        if not result.has_errors() and not result.has_validation_errors():
            kwargs = {
                "data": self.request.POST or None,
                "files": self.request.FILES or None,
                "initial": {
                    "import_file_name": import_file.tmp_storage_name,
                    "original_file_name": import_file.name,
                    "input_format": form.cleaned_data["format"],
                    "resource": form.cleaned_data.get("resource", ""),
                },
            }
            context["confirm_form"] = ie_forms.ConfirmImportForm(**kwargs)

        context["result"] = result
        context["title"] = "Import"
        context["form"] = form
        context["opts"] = self.model._meta

        return render(self.request, self.get_template_names(), context=context)


"""class ConfirmImportView(mixins.BaseImportMixin, FormView):
    form_class = ie_forms.ConfirmImportForm

    def get_import_data_kwargs(self, request, *args, **kwargs):
        
        #Prepare kwargs for import_data.
        
        form = kwargs.get("form")
        if form:
            kwargs.pop("form")
            return kwargs
        return {}

    def form_valid(self, form):
        model_name = self.kwargs.get("model_name")

        try:
            model = apps.get_model(model_name)
        except Exception:
            messages.error(self.request, "Impossible d'exporter cette table.")
            return redirect(self.request.META.get("HTTP_REFERER"))

        try:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes[model.__name__]
            )
        except:
            resource = ie_resources.modelresource_factory(
                model=model, resource_class=resource_classes["default"]
            )

        if not resource:
            messages.error(
                self.request, "Impossible d'exporter les données de cette table."
            )
            return redirect(self.request.META.get("HTTP_REFERER"))

        resource = resource()

ie_app/templates/confirm_import.html
{% extends "base.html" %}

{% block content %}
  <h2>Confirmer l'importation</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Confirmer l'importation</button>
  </form>
{% endblock %}

ie_app/templates/export_form.html
{% extends "base.html" %}
{% load static %}
{% load formsetify %}
{% load icon %}
{% load richtext %}

{% block title %} {{card_title}} {% endblock title %}

{% block stylesheet %}
<link href="{% static 'formset/css/bootstrap5-extra.css' %}" rel="stylesheet">
{% if form_collection %}
<link href="{% static 'formset/css/collections.css' %}" rel="stylesheet">
{{form_collection.media.css}}
{% else %}
{{form.media.css}}
{% endif %}
<script type="module" src="{% static 'formset/js/django-formset.js' %}" nonce="{{request.csp_nonce}}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" nonce="{{request.csp_nonce}}"></script>
{% endblock stylesheet %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{{list_url}}">{{list_of}}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{card_title}}</li>
{% endblock breadcrumb %}

{% block content %}
<div class="card mb-5">
    <div class="card-header">
        <h2>{{card_title}}</h2>
        {% block more-info %}{% endblock more-info %}
    </div>
    <div class="card-body">
        <div>
            <django-formset endpoint="{{request.path}}" csrf-token="{{csrf_token}}"
                withhold-feedback="errors warnings success">
                {% if form_collection %}
                {{form_collection}}
                {% else %}
                {% render_form form %}
                {% endif %}
                
                <div class="offset-sm-3 mt-5 mb-5">
                    {% include 'components/formset-button.html' with label="Enregistrer" color="btn-success" icon_name='"save"' process="spinner -> submit -> okay(2000) -> proceed !~ bummer(10000) -> scrollToError" %}
                    {% if can_rerender %}
                    {% include 'components/formset-button.html' with label="Enregistrer et Continuer" color="btn-info" icon_name='"refresh-cw"' process="spinner -> submit -> okay(2000) -> proceed -> reload !~ bummer(10000)" %}
                    {% endif %}
                    <a href="{{ list_url }}">{% include 'components/formset-button.html' with label="Annuler" color="btn-warning" icon_name='"x"' process="spinner -> reset -> proceed({{request.META.HTTP_REFERER}})" %}</a>
                </div>
            </django-formset>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% if form_collection %}
{{form_collection.media.js}}
{% else %}
{{form.media.js}}
{% endif %}
<script nonce="{{ request.csp_nonce }}">
    $(document).ready(function(){
        // Gestion de l'événement de changement de la case "Sélectionner tout"
        $('#select_all_checkbox').change(function() {
            var isChecked = this.checked;
            // Sélectionner ou désélectionner toutes les cases en fonction de l'état de la case "Sélectionner tout"
            $('input[name="fields_list"]').prop('checked', isChecked);
        });

        // Gestion de l'événement de changement des cases individuelles
        $('input[name="fields_list"]').change(function() {
            // Si une case individuelle est décochée, décocher la case "Sélectionner tout"
            if (!this.checked) {
                $('#select_all_checkbox').prop('checked', false);
            } else {
                // Vérifier si toutes les cases individuelles sont cochées
                var allChecked = true;
                $('input[name="fields_list"]').each(function() {
                    if (!this.checked) {
                        allChecked = false;
                        return false; // Sortir de la boucle si une case est décochée
                    }
                });
                // Définir l'état de la case "Sélectionner tout" en fonction des cases individuelles
                $('#select_all_checkbox').prop('checked', allChecked);
            }
        });
    });
</script>
{% endblock javascript %}

ie_app/templates/import.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block title %} {{title}} {% endblock %}
{% block breadcrumb %}
{{breadcrumb|safe}}
{% endblock breadcrumb %}

{% block stylesheet %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/import_base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'import_export/import.css' %}" />
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<style>
    select {
        display: inline;
    }
</style>
{% if confirm_form %}
{{ confirm_form.media }}
{% else %}
{{ form.media }}
{% endif %}
{% endblock stylesheet %}

{% block content %}
{% if confirm_form %}
<form action="{% url 'ie_app:confirm-import-view' model_name %}" method="POST">
    {% csrf_token %}
    {{ confirm_form.as_p }}
    <p>
        {% trans "Below is a preview of data to be imported. If you are satisfied with the results, click 'Confirm import'" %}
    </p>
    <div class="submit-row">
        <input type="submit" class="default" name="confirm" value="{% trans "Confirm import" %} ">
    </div>
</form>
{% else %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include "admin/import_export/resource_fields_list.html" with import_or_export="import" %}

    <fieldset class="module aligned">
        {% for field in form %}
        <div class="form-row">
            {{ field.errors }}
            {{ field.label_tag }}
            {% if field.field.widget.attrs.readonly %}
            {{ field.field.value }}
            {{ field.as_hidden }}
            {% else %}
            {{ field }}
            {% endif %}
            {% if field.field.help_text %}
            <p class="help">{{ field.field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </fieldset>

    <div class="submit-row mt-5">
        <input type="submit" class="default" value="{% translate 'Submit' %}">
    </div>
</form>
{% endif %}

{% if result %}
<div class="card mt-5">
    <div class="card-header">
        <div class="card-title">Résultat de l'importation</div>
    </div>
    <div class="card-body card-block">
        <div class="table-responsive-sm small">
            {% if result.has_errors %}
            <h2>{% translate "Errors" %}</h2>
            <ul>
                {% for error in result.base_errors  %}
                <li>
                    {{ error.error }}
                    <!-- <div class="traceback">{{ error.traceback|linebreaks }}</div> -->
                </li>
                {% endfor %}
                {% for line, errors in result.row_errors %}
                {% for error in errors %}
                <li class="import-error-li">
                    {% if "message" in import_error_display %}
                    <div class="import-error-display-message">{% translate "Line number" %}: {{ line }} -
                        {{ error.error }}</div>
                    {% endif %}
                    {% if "row" in import_error_display %}
                    <div class="import-error-display-row">{{ error.row.values|join:", " }}</div>
                    {% endif %}
                    {# if "traceback" in import_error_display #}
                    <div class="import-error-display-traceback">{{ error.traceback|linebreaks }}</div>
                    {# endif #}
                </li>
                {% endfor %}
                {% endfor %}
            </ul>

            {% elif result.has_validation_errors %}

            <h2>{% translate "Some rows failed to validate" %}</h2>

            <p>{% translate "Please correct these errors in your data where possible, then reupload it using the form above." %}
            </p>

            <table class="import-preview">
                <thead>
                    <tr>
                        <th>{% translate "Row" %}</th>
                        <th>{% translate "Errors" %}</th>
                        {% for field in result.diff_headers %}
                        <th>{{ field }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in result.invalid_rows %}
                    <tr>
                        <td>{{ row.number }} </td>
                        <td class="errors">
                            <span class="validation-error-count">{{ row.error_count }}</span>
                            <div class="validation-error-container">
                                <ul class="validation-error-list">
                                    {% for field_name, error_list in row.field_specific_errors.items %}
                                    <li>
                                        <span class="validation-error-field-label">{{ field_name }}</span>
                                        <ul>
                                            {% for error in error_list %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endfor %}
                                    {% if row.non_field_specific_errors %}
                                    <li>
                                        <span
                                            class="validation-error-field-label">{% translate "Non field specific" %}</span>
                                        <ul>
                                            {% for error in row.non_field_specific_errors %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </td>
                        {% for field in row.values %}
                        <td>{{ field }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% else %}

            <h2>{% translate "Preview" %}</h2>

            <table class="import-preview">
                <thead>
                    <tr>
                        <th></th>
                        {% for field in result.diff_headers %}
                        <th>{{ field }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                {% for row in result.valid_rows %}
                <tr class="{{ row.import_type }}">
                    <td class="import-type">
                        {% if row.import_type == 'new' %}
                        {% translate "New" %}
                        {% elif row.import_type == 'skip' %}
                        {% translate "Skipped" %}
                        {% elif row.import_type == 'delete' %}
                        {% translate "Delete" %}
                        {% elif row.import_type == 'update' %}
                        {% translate "Update" %}
                        {% endif %}
                    </td>
                    {% for field in row.diff %}
                    <td>{{ field }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
            {% endif %}

        </div>
    </div>
</div>
{% endif %}
{% endblock content %}