SIGC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views 
from xauth import views as xauth_views
from django.views.i18n import JavaScriptCatalog



MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")




urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='logout'),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path('retour/', views.back_button_view, name='back-button'),
    # path(
    #     "account-activation/<uuid:pk>/set-password/",
    #     xauth_views.SetPasswordView.as_view(),
    #     name="user-set-password",
    # ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from web import views
from xauth import views as auth_views

handler400 = "web.errors_views.handler_400_view"
handler403 = "web.errors_views.handler_403_view"
handler404 = "web.errors_views.handler_404_view"
handler500 = "web.errors_views.handler_500_view"

MEDIA_ROOT = getattr(settings, "MEDIA_ROOT")
MEDIA_URL = getattr(settings, "MEDIA_URL")
ONLINE = getattr(settings, "ONLINE")

urlpatterns = [
    path("", views.CustomRedirectView.as_view(), name="redirect-index"),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemaps},
    #     name="django.contrib.sitemaps.views.sitemap",
    # ),
    path("home/", views.IndexTemplateView.as_view(), name="index-view"),
    path("admin/", admin.site.urls),
    path("parameters/", include("parameter.urls")),
    path("import-export/", include("ie_app.urls")),
    path("auth/", include("xauth.urls")),
    path("login/", auth_views.CustomLoginView.as_view(), name="user-login"),
    path("signup/", auth_views.User2CreateView.as_view(), name="user-signup"),
    path("logout/", auth_views.CustomLogoutView.as_view(), name="user-logout"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        auth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "password-reset/request/",
        auth_views.CustomPasswordResetView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/request-done/",
        auth_views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-request-done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

xauth/urls.py
from django.urls import include, path

from xauth import views

app_name = "auth"

urlpatterns = [
    # User
    path("users/create/", views.UserCreateView.as_view(), name="user-create"),


    path("users/list/", views.UserListView.as_view(), name="user-list"),
  
    path("users/staff/list/", views.StaffListView.as_view(), name="staff-list"),
    path(
        "users/<uuid:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-update",
    ),
    path(
        "users/<uuid:pk>/edit/photo",
        views.UserProfilePhotoUpdateView.as_view(),
        name="user-update-photo",
    ),
    path(
        "users/<uuid:pk>/detail/",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<uuid:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    path(
        "users/<uuid:pk>/password/",
        views.UserUpdatePasswordView.as_view(),
        name="user-update-password",
    ),
    path(
        "users/<uuid:pk>/make-admin/",
        views.UserAdminRightView.as_view(),
        name="user-make-admin",
    ),
    path(
        "users/<uuid:pk>/send-activation-key/",
        views.UserSendSecreteKey.as_view(),
        name="user-send-key",
    ),
    # Group
    path("groups/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        views.GroupUpdateView.as_view(),
        name="group-update",
    ),
    path("groups/list/", views.GroupListView.as_view(), name="group-list"),
    path(
        "groups/<int:pk>/delete/",
        views.GroupDeleteView.as_view(),
        name="group-delete",
    ),
    path(
        "groups/<int:pk>/detail/",
        views.GroupDetailView.as_view(),
        name="group-detail",
    ),
]

xauth/views.py
from datetime import date
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.contrib.auth import views as auth_views
from django.forms import BaseModelForm
from django.http.response import HttpResponse as HttpResponse
from django.http import Http404, HttpResponseBadRequest
from django.utils import timezone
from django.contrib.auth import login as auth_login
from django.core.exceptions import ImproperlyConfigured, PermissionDenied
from django.db.models import Q, Sum, Max
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.conf import settings
from datetime import datetime
from SIGC import views as cviews
from xauth.models import User, Assign, AccountActivationSecret
from .forms import *
from formset.views import FileUploadMixin
from django.views.generic import TemplateView

# from web.mails import mail_password
from SIGC import views as cviews
from xauth import forms
from xauth import models
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView, FormView
from SIGC import (
    mails as web_mail
)
from formset.views import FormViewMixin

# Create your views here.

GENERATED_PASSWORD_LENGTH = getattr(settings, "GENERATED_PASSWORD_LENGTH", 10)
DEFAULT_FROM_EMAIL = getattr(settings, "DEFAULT_FROM_EMAIL")

# Users management



@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class AssignCreateView(cviews.CustomCreateView):
    model = models.Assign
    name = "nomination"
    form_class = forms.AssignForm
    success_url = reverse_lazy("auth:user-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        card_title = (
            f"Nomination du {user.grade.label} {user.get_full_name()}"
            if user.grade
            else f"Nomination de {user.get_full_name()}"
        )
        context["card_title"] = card_title
        return context

    def form_valid(self, form):
        office = form.cleaned_data["group_assign"]
        user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
        form.instance.user = user
        form.instance.assigner = self.request.user

        for permission in office.permissions.all():
            user.groups.add(permission)

        return super().form_valid(form)


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
) 
class RoleCreateView(cviews.CustomCreateView):
    model = models.Assign
    name = "nomination"
    form_class = forms.RoleForm
    success_url = reverse_lazy("auth:user-list")
    
    def get_template_names(self) -> list[str]:
        return ['private/user_form.html']

    def dispatch(self, request, *args, **kwargs):
        self.current_user = get_object_or_404(
            models.User, pk=self.kwargs.get(self.pk_url_kwarg)
        )
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.current_user
        
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_title'] = "Assignation de role"
        return context

    def form_valid(self, form):
        office = form.cleaned_data["group_assign"]
        form.instance.user = self.current_user
        form.instance.assigner = self.request.user
        form.instance.user.groups.add(office)

        try:
            clinic = form.cleaned_data.get("clinic")
            department = form.cleaned_data.get("department")
            form.instance.user.clinics.add(clinic)
        except:
            pass
        
        
       
        self.current_user.groups.add(office)
        return super().form_valid(form)


# @method_decorator(transaction.atomic, name="form_valid")
# @method_decorator(
#     permission_required("xauth.can_assign", raise_exception=True),
#     name="dispatch",
# )
# # class AssignUpdateView(cviews.CustomUpdateView):
#     model = models.Assign
#     name = "nomination"
#     form_class = forms.AssignForm
#     success_url = reverse_lazy("auth:user-list")

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
#         context["card_title"] = (
#             f"Nomination du {user.grade.label} {user.get_full_name()}"
#         )
#         return context

#     def form_valid(self, form):
#         office = form.cleaned_data["office"]
#         user = get_object_or_404(models.User, pk=self.kwargs.get(self.pk_url_kwarg))
#         form.instance.user = user
#         form.instance.assigner = self.request.user
#         user.groups.add(office.permissions)
#         return super().form_valid(form)


@method_decorator(transaction.atomic, name="get")
@method_decorator(
    permission_required("xauth.can_assign", raise_exception=True),
    name="dispatch",
)
class AssignRemoveView(View):

    def get_success_url(self):
        return reverse(
            "auth:user-list")
    

    def get(self, request, *args, **kwargs):
        self.user = get_object_or_404(models.User, pk=self.kwargs.get("pk"))

        if not hasattr(self.user, "assign"):
            messages.warning(request, "Aucun rôle pour cette utilisateur")
            return redirect("auth:user-list")
        else:
            assign = get_object_or_404(models.Assign, pk=self.user.assign.pk)
            self.user.groups.remove(assign.group_assign)
            assign.user = None
            assign.save()
            assign.delete()

            messages.success(request, "Rôle retirer avec succès")
            return redirect(self.get_success_url())


# @method_decorator(
#     permission_required("xauth.list_user", raise_exception=True),
#     name="dispatch",
# )
class UserListView(cviews.CustomListView):
    model = models.User
    template_name = "private/list-user.html"
    context_object_name = "users"
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = UserCreateForm()  # Assurez-vous que form est bien un objet Form
        context["can_assign"] = self.request.user.has_perm("change_right_user")
        context["deactivate_user"] = self.request.user.has_perm("deactivate_user")
        context["can_add"]=True
        context["add_url"]=reverse(
            "auth:user-create"
        )
        if self.request.user.is_staff :

            context["can_assign"] = True
            context["deactivate_user"] = True
        return context

   
    

@method_decorator(
    permission_required("xauth.list_user", raise_exception=True),
    name="dispatch",
)
class StaffListView(ListView):
    model = models.User
    name = "user"
    template_name = "private/list-staff.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["can_assign"] = self.request.user.has_perm("change_right_user")
        context["deactivate_user"] = self.request.user.has_perm("deactivate_user")
        context["card_title"] = "Liste du personnel militaire"
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by("first_name", "last_name")

        if hasattr(self.request.user, "assign"):
            queryset = queryset.filter(
                structure__in=self.request.user.assign.structure.get_children(),
                structure__isnull=False,
            )

        return queryset


@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.add_user", raise_exception=True),
    name="dispatch",
)


class UserCreateView(FileUploadMixin,cviews.CustomCreateView):
    model = models.User
    success_url = reverse_lazy("auth:user-list")
    
    def get_template_names(self) -> list[str]:
        return ['private/user_form.html']
    
    def get_form_class(self):
        if self.request.user.is_superuser:
            return forms.UserCreateForm
        return forms.UserCreateForm2
    

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["card_title"] = "Ajout d'un nouvel utilisateur"
        return context
    def form_valid(self, form):
        form.instance.is_active = False
        return super().form_valid(form)
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Passe l'utilisateur connecté au formulaire
        return kwargs




@method_decorator(transaction.atomic, name="form_valid")
@method_decorator(
    permission_required("xauth.change_user", raise_exception=True),
    name="dispatch",
)
class UserUpdateView(FileUploadMixin,cviews.CustomUpdateView):
    model = models.User
    form_class = forms.UserCreateForm

    # def get_form_kwargs(self):

xauth/templates/private/assign_module.html
{% extends "base.html" %}
{% block breadcrumb %}
    <a href="{% url 'index-view' %}">Accueil</a> &gt;
    {{ filiere.name }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Attribution de module(s) à l'enseigant(e) {{ teacher.first_name }} {{ teacher.last_name }}</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </form>
                    <a href="{% url 'auth:user-list' %}" class="btn btn-secondary">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

xauth/templates/private/detail-group.html
{% extends "models/detail.html" %}
{% load icon %}

{% block card-title %}
{{object.name}}
{% endblock card-title %}

{% block card-description %}
{{ object.permissions.all|join:"<br>" }}
{% endblock card-description %}

{% block detail %}
{% if perms.auth.change_group  %}
<a class="btn btn-sm btn-outline-success m-1" href="{% url 'auth:group-update' object.id %}">
    {% icon "edit" height="16" width="16" %}&nbsp; Modifier
</a>
{% endif %}
{% if perms.auth.delete_group  %}
<a class="btn btn-sm btn-outline-danger m-1" href="{% url 'auth:group-delete' object.id %}">
    {% icon "trash" height="16" width="16" %}&nbsp; Supprimer
</a>
{% endif %}
{% endblock detail %}

xauth/templates/private/list-group.html
{% extends "models/list.html" %}
{% load icon %}
{% load humanize %}
{% load static %}

{% block toolbar-plus %}

{% endblock toolbar-plus %}


{% block table-headers %}
<th>Nom(s)</th>
<th>Permissions</th>
{% endblock table-headers %}

{% block table-rows %}
<td>{{object.name|default_if_none:"-"}}</td>
<td>{{ object.permissions.all|join:", "|truncatewords:20 }}</td>
{% endblock table-rows %}

xauth/templates/private/list-user.html
{% extends "models/list.html" %}
{% load icon %}
{% load humanize %}
{% load static %}


{% block breadcrumb %}
<div class="breadcrumb-container">
  <ul class="breadcrumb">
      <li><a href="{% url 'index-view' %}"><i class="fa fa-home"></i> Accueil</a>
      <li><a href="{{ list_url }}">{{ list_of }}</a></li>
      <li class="active">{{ card_title }}</li>
  </ul>
</div>
{% endblock %}

{% block toolbar-plus %}
<!-- <a href="{{ add_url }}">
  <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="popover"
      data-bs-content="Nouveau" data-bs-container="body" data-bs-placement="top">
      {% icon "plus" height=option_size width=option_size %}&nbsp; Nouveau
  </button>
</a> -->
{% endblock toolbar-plus %}

{% block table-headers %}
<th>Nom</th>
<th>Email</th>
<th>Matricule</th>
<th>Rôle</th>
<th>Poste</th>
{% endblock table-headers %}
{% include 'models/paginates.html' %}
{% block table-rows %}
<td>{{object.first_name|title}} {{object.last_name|title}}</td>
<td>{{object.email}}</td>
<td>{{object.matricule}}</td>
<td>{{object.get_role}}</td>
<td>Directeur</td>
{% endblock table-rows %}

{% block other-options %}
{% if deactivate_user %}
{% if not object.is_active %}
<a href="{% url 'auth:user-send-key' object.id %}">
  <button type="button" class="btn btn-md btn-outline-secondary" data-bs-toggle="popover"
    data-bs-content="Activer le compte" data-bs-container="body" data-bs-placement="top" 
    data-toggle="tooltip" data-placement="top" title="Activer le compte">
    {% icon "key" height=option_size width=option_size %}
  </button>
</a>
{% else %}
<a href="{% url 'auth:user-send-key' object.id %}">
  <button type="button" class="btn btn-md btn-outline-danger" data-bs-toggle="popover"
    data-bs-content="Activer le compte" data-bs-container="body" data-bs-placement="top" 
    data-toggle="tooltip" data-placement="top" title="Désactiver le compte">
    {% icon "key" height=option_size width=option_size %}
  </button>
</a>
{% endif %}
{% endif %}
{% if can_assign %}
{% if object.assign %}
<a href="{% url 'auth:assign-remove' object.id %}">
  <button type="button" class="btn btn-md btn-outline-danger" data-bs-toggle="popover" data-bs-content="retirer un rôle"
    data-bs-container="body" data-bs-placement="top"  data-toggle="tooltip" data-placement="top" title="retirer un rôle">
    {% icon "briefcase" height=option_size width=option_size %}
  </button>
</a>
{% else %}
<a href="#">
  <button type="button" class="btn btn-md btn-outline-warning" data-bs-toggle="popover" data-bs-content="Donner un rôle "
    data-bs-container="body" data-bs-placement="top"  data-toggle="tooltip" data-placement="top" title="Donner un rôle">
    {% icon "briefcase" height=option_size width=option_size %}
  </button>
</a>
{% endif %}
{% endif %}

{% endblock other-options %}

xauth/templates/private/user-profile-admin-view.html
{% extends "base.html" %}
{% load static %}
{% load icon %}

{% block title %}{{ object.get_full_name }}{% endblock title %}

{% block stylesheet %}
<style>
    .profile-section {
        background-color: #f8f9fa;
    }

    .profile-card {
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0px 10px 12px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .profile-card:hover {
        transform: scale(1.02);
        box-shadow: 0px 15px 20px rgba(0, 0, 0, 0.15);
    }

    .profile-header {
        text-align: center;
        padding: 20px;
    }

    .profile-image {
        width: 135px;
        height: 135px;
        border-radius: 50%;
        object-fit: cover;
        border: 3px solid #007bff;
        transition: filter 0.3s ease;
    }

    .profile-image:hover {
        filter: brightness(0.9);
    }

    .btn-custom {
        font-size: 14px;
        padding: 8px 20px;
    }

    .btn-custom:hover {
        background-color: #0056b3;
        color: white;
        transition: background-color 0.3s ease;
    }

    .tab-content .card-body p:hover {
        color: #0056b3;
        transition: color 0.3s ease;
    }

    .col-lg-8:hover {
        background-color: #f0f0f0;
        transform: scale(1.02);
        box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease-in-out;
    }
</style>
{% endblock stylesheet %}

{% block content %}
<section class="profile-section py-5">
    <div class="container">
        <div class="row">
            <!-- Profile Summary -->
            <div class="col-lg-4">
                <div class="card profile-card mb-4">
                    <div class="profile-header">
                        {% if object.photo %}
                            <img src="{{ object.photo.url }}" alt="avatar" class="profile-image">
                        {% else %}
                            <img src="{% static 'img/profil.jpg' %}" alt="avatar" class="profile-image">
                        {% endif %}
                        <h5 class="mt-3">{{ object.get_full_name }}</h5>
                        <span class="badge bg-primary">{{ object.user_type }}</span>
                        <p class="text-muted">{{ object.grade.label }}</p>
                        <a href="{% url 'auth:user-update-photo' object.id %}"><button class="btn btn-primary btn-custom">Modifier</button></a>    
                        <button class="btn btn-outline-primary btn-custom ms-2">Message</button>
                    </div>
                </div>
            </div>

            <!-- Profile Details -->
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" href="#etat-civil" data-bs-toggle="tab">État Civil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#contact" data-bs-toggle="tab">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#competences" data-bs-toggle="tab">Compétences</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content p-4">
                        <!-- État Civil -->
                        <div class="tab-pane fade show active" id="etat-civil">
                            <div class="card-body">
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Nom :</strong></div>
                                    <div class="col-sm-9">{{ object.last_name }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Prénom(s) :</strong></div>
                                    <div class="col-sm-9">{{ object.first_name }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Matricule :</strong></div>
                                    <div class="col-sm-9">{{ object.matricule }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Date de naissance :</strong></div>
                                    <div class="col-sm-9">{{ object.birthdate|date:"SHORT_DATE_FORMAT" }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Lieu de naissance :</strong></div>
                                    <div class="col-sm-9">{{ object.birthplace }}</div>
                                </div>
                            </div>
                        </div>

                        <!-- Contact -->
                        <div class="tab-pane fade" id="contact">
                            <div class="card-body">
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Email :</strong></div>
                                    <div class="col-sm-9">{{ object.email }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Téléphone :</strong></div>
                                    <div class="col-sm-9">{{ object.phone }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Adresse :</strong></div>
                                    <div class="col-sm-9">{{ object.address }}</div>
                                </div>
                            </div>
                        </div>

                        <!-- Compétences -->
                        <div class="tab-pane fade" id="competences">
                            <div class="card-body">
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Université :</strong></div>
                                    <div class="col-sm-9">{{ object.structure_origine }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Grade :</strong></div>
                                    <div class="col-sm-9">{{ object.grade }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Statut :</strong></div>
                                    <div class="col-sm-9">{{ object.teacher_type }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>filière(s) :</strong></div>
                                    <div class="col-sm-9">{{ object.filiere }}</div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3"><strong>Module(s) :</strong></div>
                                    <div class="col-sm-9">{{ object.module }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

xauth/templates/private/user_create_review.html
{% extends 'base.html' %}

{% block content %}
  <h1>Récapitulatif de l'inscription</h1>

  <form method="POST" action="{% url 'user_create_submit' %}">
    {% csrf_token %}
    <table class="table">
      <thead>
        <tr>
          <th>Champ</th>
          <th>Valeur</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Nom</td>
          <td>{{ form_data.first_name }}</td>
        </tr>
        <tr>
          <td>Prénom</td>
          <td>{{ form_data.last_name }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>{{ form_data.email }}</td>
        </tr>
        <tr>
          <td>Téléphone</td>
          <td>{{ form_data.phone }}</td>
        </tr>
        <tr>
          <td>Adresse</td>
          <td>{{ form_data.address }}</td>
        </tr>
        <!-- Ajoutez d'autres champs ici selon votre formulaire -->
      </tbody>
    </table>

    <button type="submit" class="btn btn-success">Confirmer l'inscription</button>
    <a href="{% url 'user_create' %}" class="btn btn-warning">Modifier</a>
  </form>
{% endblock %}