SIGC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views 
from xauth import views as xauth_views
from django.views.i18n import JavaScriptCatalog



MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")




urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='logout'),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path('retour/', views.back_button_view, name='back-button'),
    # path(
    #     "account-activation/<uuid:pk>/set-password/",
    #     xauth_views.SetPasswordView.as_view(),
    #     name="user-set-password",
    # ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from web import views
from xauth import views as auth_views

handler400 = "web.errors_views.handler_400_view"
handler403 = "web.errors_views.handler_403_view"
handler404 = "web.errors_views.handler_404_view"
handler500 = "web.errors_views.handler_500_view"

MEDIA_ROOT = getattr(settings, "MEDIA_ROOT")
MEDIA_URL = getattr(settings, "MEDIA_URL")
ONLINE = getattr(settings, "ONLINE")

urlpatterns = [
    path("", views.CustomRedirectView.as_view(), name="redirect-index"),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemaps},
    #     name="django.contrib.sitemaps.views.sitemap",
    # ),
    path("home/", views.IndexTemplateView.as_view(), name="index-view"),
    path("admin/", admin.site.urls),
    path("parameters/", include("parameter.urls")),
    path("import-export/", include("ie_app.urls")),
    path("auth/", include("xauth.urls")),
    path("login/", auth_views.CustomLoginView.as_view(), name="user-login"),
    path("signup/", auth_views.User2CreateView.as_view(), name="user-signup"),
    path("logout/", auth_views.CustomLogoutView.as_view(), name="user-logout"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        auth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "password-reset/request/",
        auth_views.CustomPasswordResetView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/request-done/",
        auth_views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-request-done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

xauth/urls.py
from django.urls import include, path

from xauth import views

app_name = "auth"

urlpatterns = [
    # User
    path("users/create/", views.UserCreateView.as_view(), name="user-create"),


    path("users/list/", views.UserListView.as_view(), name="user-list"),
  
    path("users/staff/list/", views.StaffListView.as_view(), name="staff-list"),
    path(
        "users/<uuid:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-update",
    ),
    path(
        "users/<uuid:pk>/edit/photo",
        views.UserProfilePhotoUpdateView.as_view(),
        name="user-update-photo",
    ),
    path(
        "users/<uuid:pk>/detail/",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path(
        "users/<uuid:pk>/delete/",
        views.UserDeleteView.as_view(),
        name="user-delete",
    ),
    path(
        "users/<uuid:pk>/password/",
        views.UserUpdatePasswordView.as_view(),
        name="user-update-password",
    ),
    path(
        "users/<uuid:pk>/make-admin/",
        views.UserAdminRightView.as_view(),
        name="user-make-admin",
    ),
    path(
        "users/<uuid:pk>/send-activation-key/",
        views.UserSendSecreteKey.as_view(),
        name="user-send-key",
    ),
    # Group
    path("groups/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        views.GroupUpdateView.as_view(),
        name="group-update",
    ),
    path("groups/list/", views.GroupListView.as_view(), name="group-list"),
    path(
        "groups/<int:pk>/delete/",
        views.GroupDeleteView.as_view(),
        name="group-delete",
    ),
    path(
        "groups/<int:pk>/detail/",
        views.GroupDetailView.as_view(),
        name="group-detail",
    ),
]

web/templates/components/footer.html
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                Copyright &copy; 2023
            </div>
            <div class="col-sm-6 text-right">
                Designed by <a href="https://tpe.bf">Tech Pôle Expertise (TPE)</a>
            </div>
        </div>
    </div>
</footer>

web/templates/components/formset-button.html
{% load icon %}

<button type="button" withhold-feedback="errors" df-click="{{process}}" class="btn {{color}} btn-sm p-2">
    <span class="dj-button-decorator">
        {% if icon_name %}
        {% icon "{{icon_name}}" class="dj-icon" height=option_size width=option_size %}
        {% endif %}
    </span>
    &nbsp; {{label}}
</button>

web/templates/components/header.html
{% load static %}
{% load icon %}
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="#" onClick="return false;" class="navbar-toggle collapsed" data-bs-toggle="collapse"
                data-bs-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="#" onClick="return false;" class="bars"></a>
            <a class="navbar-brand" href="/">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="float-start">
                <li>
                    <a href="#" onClick="return false;" class="sidemenu-collapse">
                        {% icon "menu" height=header_size width=header_size %}
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <!-- Full Screen Button -->
                <!-- <li class="fullscreen">
                    <a href="javascript:;" class="fullscreen-btn">
                        {% icon "maximize" height=header_size width=header_size %}
                    </a>
                </li> -->
                <!-- #END# Full Screen Button -->
                <!-- #START# Notifications-->
                <!-- <li class="dropdown">
                    <a href="#" onClick="return false;" class="dropdown-toggle" data-bs-toggle="dropdown" role="button">
                        {% icon "bell" height=header_size width=header_size %}
                        <span class="notify"></span>
                        <span class="heartbeat"></span>
                    </a>
                    <ul class="dropdown-menu pullDown">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="{% static 'images/logo.jpg' %}" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">Yems First</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> il y a 14 minutes
                                            </span>
                                            <span class="menu-desc">Merci de consulter vos emails.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="{% static 'images/logo.jpg' %}" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">Ouattara Aminata</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> il y a 22 minutes
                                            </span>
                                            <span class="menu-desc">Merci de consulter vos emails.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="{% static 'images/logo.jpg' %}" width="50%" height="50%" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">M. Nikiema</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i>il y a 1 heure
                                            </span>
                                            <span class="menu-desc">Merci de consulter vos emails.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="{% static 'images/logo.jpg' %}" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">Sawadogo Rahimah</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> il y a 2 heures
                                            </span>
                                            <span class="menu-desc">Merci de consulter vos emails.</span>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#" onClick="return false;">Afficher toutes les notifications</a>
                        </li>
                    </ul>
                </li> -->
                <!-- #END# Notifications-->
                <li class="dropdown user_profile">
                    <div class="dropdown-toggle" data-bs-toggle="dropdown">
                        <img src="{% static 'images/logo.jpg' %}" width="50%" height="50%" alt="user">
                    </div>
                    <ul class="dropdown-menu pullDown">
                        <li class="body">
                            <ul class="user_dw_menu">
                                <li>
                                    <a href="{% url 'auth:user-detail' request.user.pk %}">
                                        {% icon "user" height=header_size width=header_size %}&nbsp; Profil
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        {% icon "message-square" height=header_size width=header_size %}&nbsp; Feedback
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        {% icon "help-circle" height=header_size width=header_size %}&nbsp; Aide
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'user-logout' %}">
                                        {% icon "log-out" height=header_size width=header_size %}
                                        &nbsp; Se déconnecter
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <!-- #END# Tasks -->
                <li class="float-end">
                    <a href="#" onClick="return false;" class="js-right-sidebar" data-close="true">
                        <!-- <i class="fas fa-cog"></i> -->
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

web/templates/components/list-options.html
{% load icon %}

{% if can_detail %}
<a href="{% url info_url object.slug|default:object.id %}">
    <button type="button" class="btn btn-md btn-outline-info" data-bs-toggle="popover"
        data-bs-content="Voir les détails" data-bs-container="body" data-bs-placement="top">
        {% icon "info" height=option_size width=option_size %}
    </button>
    
</a>
{% endif %}
{% if can_update %}
<a href="{% url update_url object.slug|default:object.id %}">
    <button type="button" class="btn btn-md btn-outline-success" data-bs-toggle="popover" data-bs-content="Modifier"
        data-bs-container="body" data-bs-placement="top">
        {% icon "edit" height=option_size width=option_size %}
    </button>
</a>
{% endif %}
{% if can_delete %}
<a href="{% url delete_url object.slug|default:object.id %}" class="delete-btn">
    <button type="button" class="btn btn-md btn-outline-danger" data-bs-toggle="popover" data-bs-content="Supprimer"
        data-bs-container="body" data-bs-placement="top">
        {% icon "trash" height=option_size width=option_size %}
    </button>
</a>
{% endif %}

web/templates/components/searchbar.html
{% load icon %}

{% if search_url %}
<form class="d-flex flex-row mb-5 justify-content-between" method="get" action="{{ search_url }}">
    <div>
        <input type="search" class="form-control rounded" placeholder="recherche..." aria-label="Search"
            aria-describedby="search-addon" name="query" />
    </div>
    <div>
        {% comment %}
        {% if 'query' in request.GET %}
        <a class="mb-5 link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
            href="{{search_url}}">
            Effacer&nbsp; {% icon "delete" height=option_size width=option_size %}
        </a>
        {% endif %}
        {% endcomment %}
        <div class="btn-group" role="group">
            <button type="submit" class="btn btn-sm btn-outline-primary">
                {% icon "search" height=option_size width=option_size %}&nbsp;Recherche
            </button>
            <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal"
                data-bs-target="#exampleModal">
                {% icon "filter" height=option_size width=option_size %}
            </button>
        </div>
    </div>
</form>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Filtre</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="get">
                    {{ filter.form.as_p }}
                    <button type="submit" class="btn btn-sm btn-outline-primary">Filtrer</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Fermer
                </button>
            </div>
        </div>
    </div>
</div>



{% endif %}


{% comment %}
{% if 'query' in request.GET %} value="{{request.GET.query}}" {% endif %}
{% endcomment %}

web/templates/components/searchbar3.html
{% load icon %}

{% if search_url %}
<form class="row domain-search ">
    <div class="row">
        <div class="col-md-9">
            <div class="input-group">
                <input type="search" class="form-control">
                <span class="input-group-addon"><input type="submit" value="Search" class="btn btn-primary"></span>
            </div>
        </div>
    </div>
</form>
{% endif %}


{% comment %}
{% if 'query' in request.GET %} value="{{request.GET.query}}" {% endif %}
{% endcomment %}

web/templates/components/sidebar.html
{% load icon %}
{% load static %}

<div>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="sidebar-user-panel active">
                    <div class="user-panel">
                        <div class=" image">
                            <img src="{% static 'images/avatar.png' %}" class="user-img-style" alt="User Image" />
                        </div>
                        <div class="text-center fw-bold p-2">
                            <strong>Gestion des Cliniques des Armées</strong>
                        </div>
                    </div>
                    <div class="profile-usertitle">
                        <div class="sidebar-userpic-name">
                            {{request.user.grade.label|title}} {{request.user.get_full_name|title}}
                        </div>
                        <div class="profile-usertitle-job ">
                            Corps de troupe :{{request.user.structure.label|title}} <br>
                        </div>
                        {% if request.user.assign %}
                        <div class="profile-usertitle-job ">
                            Poste: {{request.user.assign.group_assign.name|upper}}
                            ({{request.user.assign.structure.label|title}})
                        </div>
                        {% endif %}
                    </div>
                </li>
                <li {% if "home" in request.path %} class="active" {% endif %}>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <span>ACCUEIL</span>
                    </a>
                    <ul class="ml-menu">
                        <li {% if "home" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'index-view' %}">Tableau de bord</a>
                        </li>
                    </ul>
                </li>
                {% if perms.xauth.access_statistics %}
                <li {% if "statistics" in request.path %} class="active" {% endif %}>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <span>STATISTIQUES</span>
                    </a>
                    <ul class="ml-menu">
                    </ul>
                </li>
                {% endif %}

                {% if perms.xauth.access_parameter %}
                <li {% if "parameters/parameters" in request.path %} class="active" {% endif %}>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <span>PARAMÈTRES</span>
                    </a>
                    <ul class="ml-menu">
                        <li {% if "parameters/parameters/marital-statuses/" in request.path %} class="active"
                            {% endif %}>
                            <a href="#">
                                Situation matrimoniale
                            </a>
                        </li>
                        <li {% if "parameters/parameters/genders/" in request.path %} class="active" {% endif %}>
                            <a href="#">
                                Genre
                            </a>
                        </li>
                        <hr>
                        <li {% if "parameters/parameters/clinics/" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'parameter:clinic-list' %}">
                                Les cliniques
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.xauth.access_account %}
                <li {% if "auth" in request.path %} class="active" {% endif %}>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <span>UTILISATEURS</span>
                    </a>
                    <ul class="ml-menu">
                        {% if perms.xauth.list_user %}
                        <li {% if "users" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth:user-list' %}">Les utilisateurs</a>
                        </li>
                        {% endif %}
                        {% if  perms.xauth.list_group %}
                        <li {% if "groups" in request.path %} class="active" {% endif %}>
                            <a href="{% url 'auth:group-list' %}">Droit d'accès</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </aside>
</div>

web/templates/components/stat-card.html
{% load humanize %}
{% load icon %}

<div class="card2 card2-stats mb-4 mb-xl-0">
    <div class="card2-body">
        <div class="row">
            <div class="col">
                <h5 class="card2-title text-uppercase text-muted mb-0">{{label}}</h5>
                <span class="h2 font-weight-bold mb-0">{{value|intcomma}}</span>
            </div>
            <div class="col-auto">
                <div class="icon icon-shape text-dark rounded-circle shadow">
                    {% icon icon_name height=option_size width=option_size %}
                </div>
            </div>
        </div>
        <p class="mt-3 mb-0 text-muted text-sm">
            <a href="{{stat_link}}">
                <span class="text-nowrap">Voir plus</span>
            </a>
        </p>
    </div>
</div>

web/templates/components/toolbar.html
{% load icon %}

<div class="d-flex flex-row mb-5 justify-content-between btn-group">
    {% if can_add %}
    {% if multi_add %}
    <div class="dropdown">
        <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false" data-bs-toggle="popover" data-bs-content="Nouveau" data-bs-container="body"
            data-bs-placement="top">
            {% icon "plus-square" height=option_size width=option_size %}&nbsp; Nouveau
        </button>
        <ul class="dropdown-menu">
            {% for link in links %}
            <li><a class="dropdown-item" href="{{link.url}}">{{link.label}}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <div>
        <a href="{{ add_url }}">
            <button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="popover"
                data-bs-content="Nouveau" data-bs-container="body" data-bs-placement="top">
                {% icon "plus" height=option_size width=option_size %}&nbsp; Nouveau
            </button>
        </a>
    </div>
    {% endif %}
    {% endif %}
    {% if can_export %}
    <div>
        <a href="{{ export_url }}">
            <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="popover"
                data-bs-content="Exporter" data-bs-container="body" data-bs-placement="top">
                {% icon "download" height=option_size width=option_size %}&nbsp; Exporter
            </button>
        </a>
    </div>
    {% endif %}
    {% if can_print %}
    <div>
        <a href="{{ print_url }}">
            <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="popover"
                data-bs-content="Exporter" data-bs-container="body" data-bs-placement="top">
                {% icon "print" height=option_size width=option_size %}&nbsp; Imprimer
            </button>
        </a>
    </div>
    {% endif %}
    {% if can_import %}
    <div>
        <a href="{{ import_url }}">
            <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="popover"
                data-bs-content="Import" data-bs-container="body" data-bs-placement="top">
                {% icon "upload" height=option_size width=option_size %}&nbsp; Importer
            </button>
        </a>
    </div>
    <div>
        <a href="{{ model_url }}">
            <button type="button" class="btn btn-sm btn-outline-info" data-bs-toggle="popover"
                data-bs-content="Exporter une feuille vide" data-bs-container="body" data-bs-placement="top">
                {% icon "download-cloud" height=option_size width=option_size %}&nbsp; Modèle
            </button>
        </a>

    </div>

    {% endif %}
</div>